### ISSUE TITLE
Project specific commands?

### ISSUE THREAD

**Issue by rianneogi** [UziTech/terminal-commands#1]
Is there any way to set commands that are project specific? I need different commands for different projects.

**Comment by UziTech** [comment]
You could setup up multiple commands

i.e.
```json
{
  "project1:build": "some build command",
  "project2:build": "some other build command",
}
```

Would that not work for you?

**Comment by UziTech** [comment]
There is also a `${project}` placeholder if you need path to the current project

**Comment by UziTech** [comment]
@rianneogi did this solve your problem?

**Comment by rianneogi** [comment]
Yeah, I am just using multiple commands, but using project specific flex
toolbar to show only the commands for current project.
You can close the issue.

**Comment by UziTech** [comment]
sounds good. Thanks for the feedback
