### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by vescgi** [UziTech/terminal-commands#101]
Is there any way to assign shortcuts to terminal commands after adding them?
I'm trying to bind ctrl-x to the command you helped me write:
```
{
	"python3:execute": "python3 ${file}"
}

```
Thank you a lot and sorry if I'm being so annoying

**Comment by UziTech** [comment]
You can look at the [docs](https://github.com/UziTech/terminal-commands#options) for more things that you can do with the commands.

The commands can be an object with more options:

```js
{
  "namespace:action": {
    "commands": "python3 ${file}", // (required) Can be a string or an array of strings
    "key": "ctrl-x", // (optional) A default key binding
    "priority": 0, // (optional) Key binding priority. Default = 0
    "selector": "atom-workspace" // (optional) Selector to limit the key binding and context menu. Default = "atom-workspace"
  }
}
```

> Thank you a lot and sorry if I'm being so annoying

No problem, we were all beginners at one point. 😁

**Comment by vescgi** [comment]
Thanks a lot! It works like a charm, couldn't be more grateful!! 😀😀😀
