### ISSUE TITLE
Option to run a command NOT in the terminal

### ISSUE THREAD

**Issue by tobyink** [UziTech/terminal-commands#129]
It would be nice to be able to define a terminal command like:

```json
"google": {
  "command": "firefox https://www.google.com/",
  "terminal": false
}
```

And Firefox would open up and go to Google, but the terminal panel wouldn't appear in Atom.

This kind of works already, but the terminal appears briefly:

```json
"google": {
  "command": [ "firefox https://www.google.com/", "exit" ]
}
```

**Comment by UziTech** [comment]
This package is for running commands in a terminal inside of Atom. If you want to create commands just to execute a script there are other ways to do it. You don't need this packages for that. 

https://flight-manual.atom.io/api/v1.52.0/CommandRegistry/

in init.coffee for example:

```coffeescript
atom.commands.add 'atom-text-editor',
  'google': () ->
    exec = require('child_process').exec
    exec 'firefox https://www.google.com/'
```

**Comment by tobyink** [comment]
Then they won't show up on the same menu though.

**Comment by UziTech** [comment]
You can do that too. https://flight-manual.atom.io/api/v1.52.0/ContextMenuManager/

I want to keep this package focused on one thing (running commands in Atom) instead of try to have an option to do everything.
