### ISSUE TITLE
Add option to reuse existing terminal

### ISSUE THREAD

**Issue by tobyink** [UziTech/terminal-commands#130]
A new terminal is opened for every command run.

Would it be possible to set commands to run in the existing Atom terminal instead of opening a new one?

**Comment by UziTech** [comment]
That depends on the terminal you use. I use [x-terminal](https://atom.io/packages/x-terminal) and it has an option to run commands in the active terminal. terminal-commands just sends the commands, the terminal decides how to run the commands.

![image](https://user-images.githubusercontent.com/97994/97514944-ed5ed480-195d-11eb-9675-e7877ebefb7c.png)
