### ISSUE TITLE
Support for terminal-plus and terminal-tab

### ISSUE THREAD

**Issue by vfilimonov** [UziTech/terminal-commands#136]
Hello,

It seems like some terminals like [terminal-tab](https://atom.io/packages/terminal-tab) or [terminal-plus](https://atom.io/packages/terminal-plus) are not supported. On execution of command an error "No terminal loaded. Please install a terminal package. We recommend x-terminal." is shown.

Would it be possible to add support for those two?

Thank you in advance!

**Comment by UziTech** [comment]
Those packages would have to provide a [service](https://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/) like [platformioideterminal service](https://github.com/bus-stop/x-terminal#platformioideterminal-service-v110) so other packages like this one can send them commands to run.

**Comment by vfilimonov** [comment]
I see. 
What are the services that `terminal-commands` are using?  Both `atom-xterm` and `platformioIDETerminal`?

**Comment by UziTech** [comment]
`terminal-commands` supports: `runInTerminal`, `platformioIDETerminal`, `terminusTerminal`, and `terminationTerminal`

We can add more. Basically there just needs to be a way to send an array of commands to the terminal.

**Comment by UziTech** [comment]
I think `platformioIDETerminal` is the service that is supported by most packages.

**Comment by UziTech** [comment]
I'm going to close this since there is nothing this package can change to make it work. If those packages add a service and we need to add it to terminal-commands feel free to reopen this.
